{
	"charEncode":"<#if charEncode??>${charEncode}<#else>UTF-8</#if>",
	"cname":"${cname}Tab页",
	"code":"${code}",
	"createTime":<#if createTime??>${createTime}<#else>0</#if>,
	"createrId":"<#if createrId??>${createrId}<#else></#if>",
	"createrName":"<#if createrName??>${createrName}<#else></#if>",
	"crudeUIIds":"",
	"crudeUINames":"",
	"dataStoreVOList":[
		{
			"cname":"页面全局参数",
			"ename":"environmentVariable",
			"entityId":"",
			"modelType":"environmentVariable",
			"pageConstantList":[],
			"saveToSession":false,
			"verifyIdList":[]
		},
		{
			"cname":"页面传入参数",
			"ename":"pageParam",
			"entityId":"",
			"modelType":"pageParam",
			"pageConstantList":[],
			"saveToSession":false,
			"verifyIdList":[]
		},
		{
			"cname":"页面用户权限",
			"ename":"rightsVariable",
			"entityId":"",
			"modelType":"rightsVariable",
			"pageConstantList":[],
			"saveToSession":false,
			"verifyIdList":[]
		},
		{
			"cname":"页面常量",
			"ename":"pageConstantList",
			"entityId":"",
			"modelType":"pageConstant",
			"pageConstantList":[
				<#if dataStoreList.pageConstant??>
						{
							"constantDescription":"待上报列表",
							"constantName":"${dataStoreList.pageConstant.constantName}ListPageForWorkFlow",
							"constantOption":{
								"pageAttributeVOList":"[]",
								"pageModelId":"${dataStoreList.pageConstant.pageModelId}ListPageForWorkFlow",
								"url":"${dataStoreList.pageConstant.url}ListPageForWorkFlow${pageUrlSuffix}"
							},
							"constantType":"url",
							"constantValue":"'${dataStoreList.pageConstant.url}ListPageForWorkFlow${pageUrlSuffix}'"
						},
						{
							"constantDescription":"已上报列表",
							"constantName":"${dataStoreList.pageConstant.constantName}ReportedListPage",
							"constantOption":{
								"pageAttributeVOList":"[]",
								"pageModelId":"${dataStoreList.pageConstant.pageModelId}ReportedListPage",
								"url":"${dataStoreList.pageConstant.url}ReportedListPage${pageUrlSuffix}"
							},
							"constantType":"url",
							"constantValue":"'${dataStoreList.pageConstant.url}ReportedListPage${pageUrlSuffix}'"
						},
						{
							"constantDescription":"待办列表",
							"constantName":"${dataStoreList.pageConstant.constantName}ToDoListPage",
							"constantOption":{
								"pageAttributeVOList":"[]",
								"pageModelId":"${dataStoreList.pageConstant.pageModelId}ToDoListPage",
								"url":"${dataStoreList.pageConstant.url}ToDoListPage${pageUrlSuffix}"
							},
							"constantType":"url",
							"constantValue":"'${dataStoreList.pageConstant.url}ToDoListPage${pageUrlSuffix}'"
						},
						{
							"constantDescription":"已办列表",
							"constantName":"${dataStoreList.pageConstant.constantName}DoneListPage",
							"constantOption":{
								"pageAttributeVOList":"[]",
								"pageModelId":"${dataStoreList.pageConstant.pageModelId}DoneListPage",
								"url":"${dataStoreList.pageConstant.url}DoneListPage${pageUrlSuffix}"
							},
							"constantType":"url",
							"constantValue":"'${dataStoreList.pageConstant.url}DoneListPage${pageUrlSuffix}'"
						}
						,
						{
							"constantDescription":"综合查询列表",
							"constantName":"${dataStoreList.pageConstant.constantName}CompreListPage",
							"constantOption":{
								"pageAttributeVOList":"[]",
								"pageModelId":"${dataStoreList.pageConstant.pageModelId}CompreListPage",
								"url":"${dataStoreList.pageConstant.url}CompreListPage${pageUrlSuffix}"
							},
							"constantType":"url",
							"constantValue":"'${dataStoreList.pageConstant.url}CompreListPage${pageUrlSuffix}'"
						}
				</#if>
			],
			"saveToSession":false,
			"verifyIdList":[]
		}
	],
	"description":"",
	"hasMenu":false,
	"hasPermission":true,
	"includeFileList":[
		{
			"defaultReference":true,
			"fileName":"base",
			"filePath":"/cap/rt/common/base/css/base.css",
			"fileType":"css"
		},
		{
			"defaultReference":true,
			"fileName":"comtop.cap.rt",
			"filePath":"/cap/rt/common/base/css/comtop.cap.rt.css",
			"fileType":"css"
		},
		{
			"defaultReference":true,
			"fileName":"comtop.ui.min",
			"filePath":"/cap/rt/common/cui/themes/default/css/comtop.ui.min.css",
			"fileType":"css"
		},
		{
			"defaultReference":true,
			"fileName":"jquery",
			"filePath":"/cap/rt/common/base/js/jquery.js",
			"fileType":"js"
		},
		{
			"defaultReference":true,
			"fileName":"comtop.ui.min",
			"filePath":"/cap/rt/common/cui/js/comtop.ui.min.js",
			"fileType":"js"
		},
		{
			"defaultReference":true,
			"fileName":"comtop.cap.rt",
			"filePath":"/cap/rt/common/base/js/comtop.cap.rt.js",
			"fileType":"js"
		},
		{
			"defaultReference":true,
			"fileName":"cui.utils",
			"filePath":"/cap/rt/common/cui/js/cui.utils.js",
			"fileType":"js"
		},
		{
			"defaultReference":true,
			"fileName":"globalVars",
			"filePath":"/cap/rt/common/globalVars.js",
			"fileType":"js"
		},
		{
			"defaultReference":true,
			"fileName":"Taglibs",
			"filePath":"/cap/rt/common/CapRtTaglibs.jsp",
			"fileType":"jsp"
		}
	],
	"layoutVO":{
		"children":[{
			"children":[{
				"children":[{
					"children":[{
						"children":[],
						"componentModelId":"uicomponent.common.component.tab",
						"id":"uiid-3403506541936605",
						"options":{
							"label":"tab标签页",
							"tabs":"[{\"title\":\"待上报列表\",\"url\":${dataStoreList.pageConstant.constantName}ListPageForWorkFlow},{\"title\":\"已上报列表\",\"url\":${dataStoreList.pageConstant.constantName}ReportedListPage},{\"title\":\"待办列表\",\"url\":${dataStoreList.pageConstant.constantName}ToDoListPage},{\"title\":\"已办页面\",\"url\":${dataStoreList.pageConstant.constantName}DoneListPage},{\"title\":\"综合查询\",\"url\":${dataStoreList.pageConstant.constantName}CompreListPage}]",
							"uitype":"Tab"
						},
						"requireExplain":"",
						"type":"ui",
						"uiType":"Tab"
					}],
					"componentModelId":"uicomponent.layout.component.tableLayout",
					"id":"tdid-36992547424745844",
					"options":{
						"label":"单元格",
						"uitype":"Td"
					},
					"type":"layout",
					"uiType":"td"
				}],
				"id":"trid-13528874946747765",
				"options":{
					"uitype":"tr"
				},
				"type":"layout",
				"uiType":"tr"
			}],
			"id":"tableid-17232392265519902",
			"options":{
				"label":"表格布局",
				"uitype":"table"
			},
			"type":"layout",
			"uiType":"table"
		}],
		"options":{}
	},
	"menuName":"${menuName}",
	"menuType":"<#if menuType??>${menuType}<#else>1</#if>",
	"minWidth":"100%",
	"modelId":"${modelId}",
	"modelName":"${modelName}",
	"modelPackage":"${modelPackage}",
	"modelPackageId":"${modelPackageId}",
	"modelType":"${modelType}",
	"pageActionVOList":[],
	"pageAttributeVOList":[
		<#-- 页面参数集合 -->
	],
	"pageComponentExpressionVOList":[],
	"pageId":"${pageId}",
	"pageType":<#if pageType??>${pageType}<#else>1</#if>,
	"parentId":"${parentId}",
	"parentName":"${parentName}",
	"pageUIType":"framePage",
	"url":"${url}"
}